name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-heroku.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "dashboard-weather-real-time"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend" # Esto le indica que despliegue SOLO la carpeta backend
